# Generated by Django 3.1.7 on 2021-04-08 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_preguntasrespondidas_quizusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preguntasrespondidas',
            old_name='usuario',
            new_name='quizUser',
        ),
    ]
