# Generated by Django 3.1.7 on 2021-04-08 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_auto_20210408_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='maxima_marca',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=6, verbose_name='Maximo MArca'),
        ),
        migrations.AlterField(
            model_name='elegirrespuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='Quiz.pregunta'),
        ),
    ]
